### ISSUE TITLE
Video Tutorial

### ISSUE THREAD

**Issue by Jvalal-zz** [stefanjudis/sketch-contentful#4]
Is there a quick video on how to do this? the animated gif is tough to see and I can't exactly follow your instructions. thanks

**Comment by stefanjudis** [comment]
There is not video tutorial available. :/ 

And while this was a working prototype I can not really recommend using it... Bringing Contentful into sketch is a rocket task that I was not able to do on the side. Sorry about that.

**Comment by Jvalal-zz** [comment]
got it. thanks. What do you mean by "Rocket Task"?  Maybe it's easier now

**Comment by stefanjudis** [comment]
Sketch plugins had to be written in AppleScript (when I remember the name correctly) and this was extremely painful for me because it was not really documented. 

Additionally, maintaining sketch files with content is a very nice idea, but there a quickly cases were it becomes tricky. The naming convention I came up with was a nice idea but is def nothing scalable. 

Hope that's understandable. 😊

**Comment by Jvalal-zz** [comment]
sort of. I may just be able to point to some JSON, similarly to this. 

https://medium.com/@yoobi55/design-json-data-with-sketch-eecae8749709
